# Generated by Django 5.0.6 on 2024-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('ethic', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction', models.TextField(blank=True, default=None, null=True)),
                ('methodology', models.TextField(blank=True, default=None, null=True)),
                ('result', models.TextField(blank=True, default=None, null=True)),
                ('conclusion', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'abstract',
            },
        ),
        migrations.CreateModel(
            name='AbstractReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, default=None, null=True)),
                ('subcategory', models.TextField(blank=True, default=None, null=True)),
                ('classification', models.SmallIntegerField(blank=True, default=0)),
                ('keyword', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction', models.TextField(blank=True, default=None, null=True)),
                ('methodology', models.TextField(blank=True, default=None, null=True)),
                ('result', models.TextField(blank=True, default=None, null=True)),
                ('conclusion', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'abstractReviewer',
            },
        ),
        migrations.CreateModel(
            name='ClinicCaseAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('ethic', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction', models.TextField(blank=True, default=None, null=True)),
                ('resume', models.TextField(blank=True, default=None, null=True)),
                ('discussion', models.TextField(blank=True, default=None, null=True)),
                ('conclusion', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'clinic_case',
            },
        ),
        migrations.CreateModel(
            name='ClinicCaseAbstractReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, default=None, null=True)),
                ('subcategory', models.TextField(blank=True, default=None, null=True)),
                ('classification', models.SmallIntegerField(blank=True, default=0)),
                ('keyword', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction', models.TextField(blank=True, default=None, null=True)),
                ('resume', models.TextField(blank=True, default=None, null=True)),
                ('discussion', models.TextField(blank=True, default=None, null=True)),
                ('conclusion', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'clinicReviewer',
            },
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('institution', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'coauthor',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'presentation',
            },
        ),
        migrations.CreateModel(
            name='ProgrammaticEvaluationAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('ethic', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction', models.TextField(blank=True, default=None, null=True)),
                ('intervention', models.TextField(blank=True, default=None, null=True)),
                ('methodology', models.TextField(blank=True, default=None, null=True)),
                ('result', models.TextField(blank=True, default=None, null=True)),
                ('lessons', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'programmatic_evaluation',
            },
        ),
        migrations.CreateModel(
            name='ProgrammaticEvaluationAbstractReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, default=None, null=True)),
                ('subcategory', models.TextField(blank=True, default=None, null=True)),
                ('classification', models.SmallIntegerField(blank=True, default=0)),
                ('keyword', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction', models.TextField(blank=True, default=None, null=True)),
                ('intervention', models.TextField(blank=True, default=None, null=True)),
                ('methodology', models.TextField(blank=True, default=None, null=True)),
                ('result', models.TextField(blank=True, default=None, null=True)),
                ('lessons', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'programmaticReviewer',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
