# Generated by Django 5.0.6 on 2024-07-09 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstract',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.subcategory'),
        ),
        migrations.AddField(
            model_name='abstractreviewer',
            name='abstract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.abstract'),
        ),
        migrations.AddField(
            model_name='abstractreviewer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniccaseabstract',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniccaseabstract',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category'),
        ),
        migrations.AddField(
            model_name='cliniccaseabstract',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.subcategory'),
        ),
        migrations.AddField(
            model_name='cliniccaseabstractreviewer',
            name='clinicCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.cliniccaseabstract'),
        ),
        migrations.AddField(
            model_name='cliniccaseabstractreviewer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniccaseabstract',
            name='coauthor',
            field=models.ManyToManyField(to='resume.coauthor'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='coauthor',
            field=models.ManyToManyField(to='resume.coauthor'),
        ),
        migrations.AddField(
            model_name='cliniccaseabstract',
            name='keyword',
            field=models.ManyToManyField(to='resume.keyword'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='keyword',
            field=models.ManyToManyField(to='resume.keyword'),
        ),
        migrations.AddField(
            model_name='cliniccaseabstractreviewer',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.presentation'),
        ),
        migrations.AddField(
            model_name='cliniccaseabstract',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.presentation'),
        ),
        migrations.AddField(
            model_name='abstractreviewer',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.presentation'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.presentation'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstract',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstract',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstract',
            name='coauthor',
            field=models.ManyToManyField(to='resume.coauthor'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstract',
            name='keyword',
            field=models.ManyToManyField(to='resume.keyword'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstract',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.presentation'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstract',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.subcategory'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstractreviewer',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.presentation'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstractreviewer',
            name='programmaticEvaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.programmaticevaluationabstract'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstractreviewer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstractreviewer',
            name='status',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.status'),
        ),
        migrations.AddField(
            model_name='programmaticevaluationabstract',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.status'),
        ),
        migrations.AddField(
            model_name='cliniccaseabstractreviewer',
            name='status',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.status'),
        ),
        migrations.AddField(
            model_name='cliniccaseabstract',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.status'),
        ),
        migrations.AddField(
            model_name='abstractreviewer',
            name='status',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.status'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.status'),
        ),
        migrations.AlterUniqueTogether(
            name='programmaticevaluationabstractreviewer',
            unique_together={('reviewer', 'programmaticEvaluation')},
        ),
        migrations.AlterUniqueTogether(
            name='cliniccaseabstractreviewer',
            unique_together={('reviewer', 'clinicCase')},
        ),
        migrations.AlterUniqueTogether(
            name='abstractreviewer',
            unique_together={('reviewer', 'abstract')},
        ),
    ]
