# Generated by Django 5.0.6 on 2024-07-09 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_user_name', models.CharField(blank=True, max_length=128)),
                ('last_user_name', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(max_length=32, null=True)),
                ('nationality', models.CharField(default='Moçambique', max_length=64)),
                ('province', models.CharField(default='Maputo', max_length=64)),
                ('district', models.CharField(default='Kaphumo', max_length=64)),
                ('city', models.CharField(default='Maputo', max_length=64)),
                ('profession', models.CharField(max_length=258)),
                ('provenance', models.CharField(max_length=258)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('contact', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('groups', models.ManyToManyField(to='auth.group')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
